description: >
  This is an arm executor running ubuntu.
machine:
  image: 'ubuntu-2004:<<parameters.tag>>'
  resource_class: arm.<<parameters.resource_size>>
  docker_layer_caching: true
parameters:
  tag:
    default: current
    description: >
      Pick a specific ubuntu 20.04 image variant:
      https://hub.docker.com/r/ubuntu-2004/tags
    type: string
  resource_size:
    default: "medium"
    description: >
      Pick a specific resource class size:
      
      Must be one of "medium", "large", "xlarge", "2xlarge".
    type: enum
        type: enum
    enum: ["medium", "large", "xlarge", "2xlarge"]